### ISSUE TITLE
Magento patch SUPEE-8967 is out

### ISSUE THREAD

**Issue by patrick-yi-82** [brentwpeterson/magento-patches#13]
Mastercard 2 Series BIN: Bank Identification Numbers Range Update
(Uploaded: 5/2/2017 4:02 AM)

SUPEE-8967 for EE 1.9.0.0-1.14.2.4

PATCH_SUPEE-8967_EE_1.13.1.0_v1-2017-05-02-06-07-20.sh

SUPEE-8967: This patch provides Magento support for MasterCard’s updated range of BIN (card) numbers. It applies only to Magento versions prior to EE 1.14.3.0. This fix is already included in Magento EE 1.14.3.0 and later releases. 
For EE 1.9.0.0, please install patch PATCH_SUPEE-2725_EE_1.9.0.0_v1.sh before installing PATCH_SUPEE-8967_EE_1.13.1.0_v1.sh. 
For EE 1.9.1.0 - EE 1.11.2.0, please install PATCH_SUPEE-2725_EE_1.9.1.1-EE_1.11.2.0_v2.sh before installing PATCH_SUPEE-8967_EE_1.13.1.0_v1.sh.
For EE 1.12.0.0 - EE 1.13.1.0, please install patch PATCH_SUPEE-1049_EE_1.12.0.2_v2.sh before installing PATCH_SUPEE-8967_EE_1.13.1.0_v1.sh. 
For EE 1.14.0.0 - EE 1.14.2.4, you just need to install this patch 8967_EE_1.13.1.0_v1.sh.

**Comment by brentwpeterson** [comment]
Patrick, thank you for bringing this to my attention. I have added the patch to the repo under 1.13 and 1.9. Please let me know if I miss any others
