### ISSUE TITLE
SUPEE-10384 is out

### ISSUE THREAD

**Issue by jonashrem** [brentwpeterson/magento-patches#20]
See https://magento.com/security/patches/supee-10266 

Note: SUPEE-10266 for Magento Commerce (Enterprise Edition) includes a fix for a functional issues MPERF-9685, related to checkout with a zero order amount. This fix is not included in release 1.14.3.6. However, in some cases, SUPEE-10266 can cause issues in the checkout process. Specifically, if a customer enables the Add gift options checkbox during checkout, the checkout process will not progress beyond the payments step. Magento released a fix for this issue as a new patch SUPEE-10384, that needs to be installed on top of SUPEE-10266. 

Also referenced here https://magento.stackexchange.com/questions/193279/security-patch-supee-10266-possible-issues

**Comment by brentwpeterson** [comment]
Sorry it took so long to merge this.
