### ISSUE TITLE
Probably Incomplete Sections

### ISSUE THREAD

**Issue by Samuel291** [brentwpeterson/magento-patches#22]
Hello, my name is Samuel
I've checked that the lines below are probably incomplete
This can probable cause magento errors

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L214 `@@ -96,7 +96,10 @@ class Mage_Adminhtml_Block_Widget_Form_Container extends Mage_Adminhtml_Block_Widget_Container`

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L230 `
@@ -51,6 +51,13 @@ class Mage_Adminhtml_Controller_Action extends Mage_Core_Controller_Varien_Action`

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L244 `
@@ -162,7 +169,7 @@ class Mage_Adminhtml_Controller_Action extends Mage_Core_Controller_Varien_Action`

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L374 `
@@ -64,6 +64,10 @@ class Mage_Adminhtml_Newsletter_QueueController extends Mage_Adminhtml_Controller_Action`

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L389 `
@@ -142,6 +142,10 @@ class Mage_Adminhtml_Newsletter_TemplateController extends Mage_Adminhtml_Controller_Action`

https://github.com/brentwpeterson/magento-patches/blob/31fd79b53e7c166398488aab65e06d239059be50/CE1.8/PATCH_SUPEE-10266_CE_1.8.1.0_v1-2017-09-13-06-28-08.sh#L541 `
@@ -152,4 +152,20 @@ class Mage_Sales_Model_Resource_Order_Item_Collection extends Mage_Sales_Model_Resource_Order_Collection_Abstract`

Thank you for your attention.

**Comment by brentwpeterson** [comment]
I re-downloaded the patch from https://magento.com/tech-resources/download

and then committed it to the repo.

There is no difference in the file.

I would suggest that you try the same to see if it resolves your issue
