### ISSUE TITLE
10975 missing for ee1.12

### ISSUE THREAD

**Issue by msanchez-sqli** [brentwpeterson/magento-patches#42]

**Comment by brentwpeterson** [comment]
@msanchez-sqli sorry for the long delay on the reply. I will start searching for this

**Comment by brentwpeterson** [comment]
Added 

PATCH_SUPEE-10975_EE_v1.12.0.0_v1-2018-11-27-10-34-11.sh
PATCH_SUPEE-10975_EE_v1.12.0.2_v1-2018-11-27-10-36-30.sh

**Comment by msanchez-sqli** [comment]
thank you
