### ISSUE TITLE
Missing 10888 for ee1.14.3.6

### ISSUE THREAD

**Issue by dani7115** [brentwpeterson/magento-patches#43]
Missing 10888 for ee1.14.3.6

**Comment by brentwpeterson** [comment]
I added PATCH_SUPEE-10888_EE_v1.14.3.7_v1-2018-09-19-03-10-57.sh which covers version EE 1.14.3.4-1.14.3.7

**Comment by dani7115** [comment]
Ooh thanks bro. Great
