### ISSUE TITLE
SUPEE-8788 missing for EE1.14.3.2

### ISSUE THREAD

**Issue by dani7115** [brentwpeterson/magento-patches#44]
I need this

**Comment by brentwpeterson** [comment]
@dani7115 I also want to tell you that the majority of these are available from Magento (If you are waiting for me to add missing ones)  You can download it and create a PR to add it

**Comment by brentwpeterson** [comment]
@dani7115 This is the latest patch for 1.14 https://github.com/brentwpeterson/magento-patches/blob/master/EE1.14/PATCH_SUPEE-8788_EE_1.14.2.4_v2-2016-10-14-09-37-37.sh

If you feel like a newer one exists please open an a new ticket with Magento and ask for it
