### ISSUE TITLE
Wrong patch for supee 11086 on magento 1.8.0

### ISSUE THREAD

**Issue by TheTravelingTrainer** [brentwpeterson/magento-patches#46]
1.8.0 should link to the patch: PATCH_SUPEE-11086_CE_1.9.1.0_v1.sh

Not to the patch: PATCH_SUPEE-11086_CE_1.7.0.2_v1-2019-03-26-03-02-36.sh

See: https://magento.stackexchange.com/questions/268967/supee-11086-for-1-8-x/268994#268994

**Comment by TheTravelingTrainer** [comment]
1.8.0 should link to the patch: PATCH_SUPEE-11086_CE_1.9.1.0_v1.sh

Not to the patch: PATCH_SUPEE-11086_CE_1.7.0.2_v1-2019-03-26-03-02-36.sh

See: https://magento.stackexchange.com/questions/268967/supee-11086-for-1-8-x/268994#268994

**Comment by brentwpeterson** [comment]
Can you open a pull request?
