### ISSUE TITLE
Zend Security Upgrade patch for EE?

### ISSUE THREAD

**Issue by mhadianfard** [brentwpeterson/magento-patches#5]
Great resource you've put together Brent!

Curious if there's a `Zend Security Upgrade` patch available for EE versions at all? The top grid in the readme file mentions it on the right-most column.

Thanks :)

**Comment by brentwpeterson** [comment]
i have now submitted all the patches that I know about. Please let me know specific patch numbers if you need them. I will try to find them.

Brent
