### ISSUE TITLE
Missing SUPEE-11155 for EE

### ISSUE THREAD

**Issue by chevyinasia** [brentwpeterson/magento-patches#53]
Missing SUPEE-11155 for EE

**Comment by wagento** [comment]
Do you have it?

**Comment by chevyinasia** [comment]
Wish I did.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Team Wagento <notifications@github.com> Date: 5/8/20  6:49 PM  (GMT+07:00) To: brentwpeterson/magento-patches <magento-patches@noreply.github.com> Cc: *****, Author <author@noreply.github.com> Subject: Re: [brentwpeterson/magento-patches] Missing SUPEE-11155 for EE (#53) 
Do you have it?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brentwpeterson/magento-patches/issues/53#issuecomment-625777996",
"url": "https://github.com/brentwpeterson/magento-patches/issues/53#issuecomment-625777996",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wagento** [comment]
I have pushed all the 1.14 patches

**Comment by wagento** [comment]
All the 11155 patch are there now

**Comment by brentwpeterson** [comment]
Closing this
