### ISSUE TITLE
PHP 7.2 Support Patches for Magento 1 EE

### ISSUE THREAD

**Issue by artmouse** [brentwpeterson/magento-patches#56]
Hello!
These patches are missing:

    PATCH-1.14.2.0-1.14.2.4_PHP7.2_v2
    PATCH-1.14.3.0_PHP7.2_v2
    PATCH-1.14.3.1-1.14.3.9_PHP7.2_v2

Is it possible to add them too?

**Comment by brentwpeterson** [comment]
Yes they have been added! 

Thanks
