### ISSUE TITLE
SUPEE-6788 Site shutdown random

### ISSUE THREAD

**Issue by ajmerainfo** [brentwpeterson/magento-patches#6]
My site shutdown randomly. Many pages are working fine but many images and home mostly stop working.

We are still talking with magento team but still they could not figure it out.

Last response from them

> He says that he noticed you have installed custom module 'Innoexts_Warehouse' that adds column 'stock_id' to several tables, some core functionality is not compatible with these changes and could bring the site down.
> Disabling this module in 'app/etc/modules/Innoexts_Warehouse.xml' WILL NOT HELP, because database structure will not be reverted.
> He recommends you ask support from the module vendor/supplier to revert database changes or fix that module.
> 
> My engineer recommends you disable this customization, next, remove record by id 2 from table cataloginventory_stock. Also, according to install/update scripts from directory:
> 
> app/code/local/Innoexts/Warehouse/sql/warehouse_setup/.php\* 
> You should remove all changes which was done by custom module from magento tables.

**Comment by brentwpeterson** [comment]
This is only for patches, not for Magento support. Please use Stackexhange to get quicker answers.
