### ISSUE TITLE
SUPEE-11346 is missing

### ISSUE THREAD

**Issue by denis-zyk** [brentwpeterson/magento-patches#61]
Hi, I've stumbled upon your repo when I was searching for M1 patches, and now I couldn't find the latest patch SUPEE-11346 - neither for CE, nor for EE. The patch is mentioned there: https://helpx.adobe.com/security/products/magento/apsb20-41.html

Do you have any plans to add SUPEE-11346 patch to the repo?

**Comment by luckeydime** [comment]
Hey, 

I will check and get it added to the repo. 

Thanks, 
Mindi

**Comment by toddliningerdesign** [comment]
I know Nexcess maintains a patch archive of their own: https://pubfiles.nexcess.net/magento/patches/. The SUPEE-11346 patches for CE can be found there.
