### ISSUE TITLE
8778 Questions and Issues

### ISSUE THREAD

**Issue by ghost** [brentwpeterson/magento-patches#8]
Hello,

I was hoping that some advice could be given for installing the new 8788 patches. I understand the two steps:
- Install SUPEE-3941 (if not installed yet) - that one makes sense
- Revert SUPEE-1533 (if installed) - this is such an old patch why does this need to be reverted?
- Revert SUPEE-8788 v1 - has already been installed. But as we use version control there would be no reason to keep the patch file in the repository we remove the file once it has been patched. Then commit those changes. But I have noticed that it says to revert v1. So what would the process to revert the patch.
- Install SUPEE-8788 v2 - this once makes sense. Is there likely to be any updates or surprises, say a version 3 in the coming weeks? Also what is the current process with Enterprise Edition.

Thanks,

Rob

There is also syntax errors: sh PATCH_SUPEE-8788_CE_1.9.0.1_v1-2016-10-11-06-57-03.sh 
PATCH_SUPEE-8788_CE_1.9.0.1_v1-2016-10-11-06-57-03.sh: 6: PATCH_SUPEE-8788_CE_1.9.0.1_v1-2016-10-11-06-57-03.sh: Syntax error: newline unexpected

**Comment by brentwpeterson** [comment]
Robert, 

Your best bet on issues with patches is to open a ticket on http://magento.stackexchange.com/ 

(Unless it is an EE site)

Let me know if you need help in doing this.

Brent

**Comment by ghost** [comment]
Can you remove my comment if possible, as I dont want it to show in my contributed list.
